services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=myplaydb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuserENG'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: